const Facts = [
    "The first computer programmer was Ada Lovelace, a woman.",
    "The 'bug' in computer science came from a moth in ENIAC.",
    "Robotic prosthetics enhance mobility for amputees.",
    "Robotics contributes to space exploration and colonization.",
    "The '404 Not Found' error was named after room 404.",
    "Light travels at 299,792 kilometers per second.",
    "Gravity makes objects fall at the same rate.",
    "Sound can't travel through a vacuum.",
    "Atoms are mostly empty space.",
    "Time dilation occurs near massive objects.",
    "A cat can be both dead and alive (Schrodinger's cat).",
    "Inertia is a property of matter.",
    "Electrons orbit the nucleus in energy levels.",
    "Quantum entanglement is instant communication between particles.",
    "The universe is expanding.",
    "Airplanes' black boxes are orange for visibility.",
    "The Wright brothers' first flight was 12 seconds long.",
    "Robotics advancements continue to shape the future.",
    "Lightning can strike the same place twice.",
    "Freedom is the oxygen of the soul.",
    "Liberty means responsibility. That is why most men dread it.",   
    "Freedom is the right to tell people what they do not want to hear.",
    "The first domain name ever registered was symbolics.com.",
    "The first web page went live on August 6, 1991.",
    "Space is not completely empty; it has micrometeoroids.",
    "The Concorde was a supersonic passenger airliner.",
    "The sound barrier was broken by Chuck Yeager in 1947.",
    "Saturn V is the most powerful rocket ever built.",
    "A group of flamingos is called a flamboyance.",
    "A panda's diet consists almost entirely of bamboo.",
    "Honey never spoils; archaeologists found edible honey in ancient tombs.",
    "A newborn kangaroo is the size of a lima bean.",
    "Cows have best friends and can get stressed when separated.",
    "Penguins can jump up to 6 feet in the air.",
    "A snail can sleep for three years.",
    "Ants never sleep and don't have lungs.",
    "Dragonflies have six legs but can't walk.",
    "Koalas have fingerprints similar to humans.",
    "Astronauts grow taller in space due to microgravity.",
    "Aircraft tires are inflated with nitrogen for stability.",
    "A shooting star is a meteoroid burning in Earth's atmosphere.",
    "The 'right stuff' refers to qualities of test pilots.",
    "The Bell X-1 was the first aircraft to break the sound barrier.",
    "The Apollo lunar module had only two computers.",
    "Matter and energy are interchangeable (E=mc^2).",
    "Black holes have intense gravitational pull.",
    "Falling objects accelerate due to gravity.",
    "Objects in motion stay in motion (Newton's first law).",
    "Every action has an equal and opposite reaction (Newton's third law).",
    "Magnetic fields can repel or attract.",
    "The Doppler effect changes frequency with motion.",
    "Heat is the transfer of thermal energy.",
    "Einstein received the Nobel Prize for the photoelectric effect.",
    "The uncertainty principle is fundamental in quantum mechanics.",
    "Wi-Fi technology was developed by Australian scientists in 1992.",
    "The computer mouse was inspired by radar tracking devices.",
    "The first computer mouse was made of wood in 1964.",
    "The world's first computer was created in 1822 by Babbage.",
    "The first computer bug was a moth found in Harvard's Mark II.",
    "Ctrl+Alt+Del was designed by David Bradley at IBM.",
    "The first graphical web browser was Mosaic, in 1993.",
    "The 'I'm Feeling Lucky' button on Google bypasses search results.",
    "The first computer language was Fortran, developed in 1957.",
    "The first computer hard disk was only 5 MB.",
    "The space key on keyboards was first used in typewriters.",
    "The first computer-generated movie was 'Westworld' in 1973.",
    "The first computer mouse cost $300 in 1981.",
    "JavaScript was created by Brendan Eich in 10 days.",
    "Linux was created by Linus Torvalds in 1991.",
    "The first computer virus was created in 1986.",
    "The first computer mouse had two buttons.",
    "Python is named after Monty Python's Flying Circus.",
    "Java is not the same as JavaScript.",
    "Google's original name was Backrub.",
    "Bluetooth is named after a medieval king.",
    "JavaScript was initially named Mocha.",
    "The first domain name was registered in 1985.",
    "The first computer bug was a moth.",
    "NASA's Apollo 11 used a 1MHz computer.",
    "Gorillas can catch human colds and other illnesses.",
    "A group of owls is called a parliament.",
    "The first computer mouse with a ball was introduced in 1972.",
    "The first computer made for personal use was the Altair 8800.",
    "Honey never spoils; archaeologists found edible honey in ancient tombs.",
    "The Earth's core is as hot as the surface of the Sun.",
    "Bananas are berries, but strawberries aren't true berries.",
    "Honeybees can recognize human faces and remember them for months.",
    "A day on Venus is longer than a year on Earth.",
    "Octopuses have three hearts and blue blood.",
    "Cows have best friends and can become stressed when separated.",
    "The shortest war in history lasted only 38 to 45 minutes.",
    "The blue whale's tongue weighs as much as an elephant.",
    "Bees can recognize human faces.",
    "Sloths take two weeks to digest a meal.",
    "Caterpillars liquefy and reorganize in the chrysalis.",
    "Oysters can change gender depending on environmental factors.",
    "The Earth is about 4.54 billion years old.",
    "A group of flamingos is called a 'flamboyance.'",
    "The first computer virus in the wild was in 1987.",
    "The first computer game was created in 1962 by Steve Russell.",
    "The longest domain name registered is 63 characters.",
    "The first webcam was used to monitor a coffee pot.",
    "The first computer sold commercially was UNIVAC I in 1951.",
    "The first computer with a GUI was the Xerox Alto.",
    "The first computer animation was 'Hummingbird' in 1967.",
    "The first computer virus for MS-DOS was Brain in 1986.",
    "A group of crows is called a murder.",
    "The hummingbird is the only bird that can fly backward.",
    "Octopuses have three hearts and blue blood.",
    "Bananas are berries, but strawberries aren't true berries.",
    "A baby puffin is called a puffling.",
    "Butterflies taste with their feet.",
    "ENIAC, the first computer, weighed over 27 tons.",
    "QWERTY keyboard slows typing to prevent typewriter jams.",
    "The average person's left hand does 56% of typing.",
    "The Internet's initial name was ARPANET, created in 1969.",
    "The mouse was invented by Douglas Engelbart in 1964.",
    "A byte is 8 bits, representing a single character in computing.",
    "The first computer virus was created in 1983.",
    "The Konami Code (↑ ↑ ↓ ↓ ← → ← → B A) is famous.",
    "AI robots, like Sophia, simulate human-like intelligence.",
    "Tiny robots, nanobots, operate on a microscopic scale.",
    "Boston Dynamics' Spot is a versatile robotic dog.",
    "Penguins propose to their mates with pebbles.",
    "Horses can't vomit.",
    "Dolphins have individual names for each other.",
    "A single rainforest can produce 20% of Earth's oxygen.",
    "Giraffes have the same number of neck vertebrae as humans.",
    "Cheetahs can go from 0 to 60 mph in three seconds.",
    "Starfish don't have a brain.",
    "Elephants are the only animals that can't jump.",
    "The Eiffel Tower can be 15 cm taller during the summer.",
    "A single rainforest can produce 20% of the world's oxygen.",
    "A teaspoonful of a neutron star weighs about 6 billion tons.",
    "A bolt of lightning is six times hotter than the sun.",
    "The smell of freshly-cut grass is a plant distress call.",
    "A day on Mars is only slightly longer than on Earth.",
    "A shark can detect one part of blood in 100 million.",
    "A cubic inch of neutron star material would weigh 6 billion tons.",
    "The human brain can generate about 20 watts of electrical power.",
    "The Earth's atmosphere weighs about 5.5 quadrillion tons.",
    "Lightning can strike the same place twice.",
    "A spoonful of a neutron star would weigh about six billion tons.",
    "The speed of light is about 186,282 miles per second.",
    "Honey never spoils; archaeologists found edible honey in ancient tombs.",
    "The Earth's core is as hot as the surface of the Sun.",
    "Bananas are berries, but strawberries aren't true berries.",
    "Honeybees can recognize human faces and remember them for months.",
    "A day on Venus is longer than a year on Earth.",
    "Octopuses have three hearts and blue blood.",
    "Cows have best friends and can become stressed when separated.",
    "A day on Venus is longer than a year.",
    "Jupiter's Great Red Spot is a giant storm.",
    "The Sun is 99.86% of the solar system's mass.",
    "Saturn's rings are made mostly of ice particles.",
    "The Moon is moving away from Earth over time.",
    "Neptune's winds are the fastest in the solar system.",
    "Astronauts experience 'space fever' in microgravity.",
    "Mercury has a day-night temperature difference of 600°C.",
    "The Milky Way has billions of stars and planets.",
    "Space is not completely silent; it has some sound.",
    "The shortest war in history lasted only 38 to 45 minutes.",
    "The Earth is about 4.54 billion years old.",
    "A group of flamingos is called a 'flamboyance.'",
    "The Eiffel Tower can be 15 cm taller during the summer.",
    "A single rainforest can produce 20% of the world's oxygen.",
    "A teaspoonful of a neutron star weighs about 6 billion tons.",
    "Zero is the only number that cannot be represented in Roman numerals.",
    "111,111,111 x 111,111,111 = 12,345,678,987,654,321.",
    "A 'googol' is 10 to the power of 100.",
    "Pi (π) is the ratio of a circle's circumference to its diameter.",
    "Zero is an even number.",
    "A 'jiffy' is an actual unit of time, equal to 1/100th of a second.",
    "Mathematics is the language of the universe.",
    "The number 6 is the smallest perfect number.",
    "A 'googolplex' is 10 to the power of a googol.",
    "The infinity symbol (∞) is called a lemniscate.",
    "In binary code, 1 kilobyte is 1024 bytes, not 1000.",
    "A palindrome is a number that reads the same backward as forward.",
    "The golden ratio (phi) is approximately 1.618033988749895.",
    "A 'quartodecillion' is 1 followed by 45 zeros.",
    "A bolt of lightning is six times hotter than the sun.",
    "The smell of freshly-cut grass is a plant distress call.",
    "A day on Mars is only slightly longer than on Earth.",
    "A shark can detect one part of blood in 100 million.",
    "A cubic inch of neutron star material would weigh 6 billion tons.",
    "The human brain can generate about 20 watts of electrical power.",
    "The Earth's atmosphere weighs about 5.5 quadrillion tons.",
    "Lightning can strike the same place twice.",
    "A spoonful of a neutron star would weigh about six billion tons.",
    "The speed of light is about 186,282 miles per second.",
    "Honey never spoils.",
    "Bananas are berries; strawberries aren't true berries.",
    "Octopuses have three hearts.",
    "The Eiffel Tower can be 15 cm taller during summer.",
    "A group of flamingos is called a 'flamboyance.'",
    "A teaspoonful of neutron star material weighs 6 billion tons.",
    "A single rainforest can produce 20% of the world's oxygen.",
    "The smell of freshly-cut grass is a plant distress call.",
    "Robotics began in ancient times with automatons.",
    "Drones are unmanned aerial vehicles used in robotics.",
    "Soft robotics mimic natural movements with flexible materials.",
    "Robots can assist in dangerous and repetitive tasks.",
    "Chatbots are AI-powered robots for conversation.",
    "Exoskeletons enhance human strength and mobility.",
    "Self-driving cars use robotics for autonomous navigation.",
    "Drone deliveries are explored for efficient logistics.",
    "Freedom is nothing but a chance to be better.",
    
];

export function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
}

export default Facts;